// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw-bM3HL3BMnLRitaJ779Sj2jO6v5iz6Y',
    appId: '1:389677615356:web:YOUR_WEB_APP_ID',
    messagingSenderId: '389677615356',
    projectId: 'shehercircle',
    authDomain: 'shehercircle.firebaseapp.com',
    storageBucket: 'shehercircle.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw-bM3HL3BMnLRitaJ779Sj2jO6v5iz6Y',
    appId: '1:389677615356:android:33ff97057be81444262f79',
    messagingSenderId: '389677615356',
    projectId: 'shehercircle',
    storageBucket: 'shehercircle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw-bM3HL3BMnLRitaJ779Sj2jO6v5iz6Y',
    appId: '1:389677615356:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '389677615356',
    projectId: 'shehercircle',
    storageBucket: 'shehercircle.firebasestorage.app',
    iosBundleId: 'com.example.sheHerCircle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw-bM3HL3BMnLRitaJ779Sj2jO6v5iz6Y',
    appId: '1:389677615356:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '389677615356',
    projectId: 'shehercircle',
    storageBucket: 'shehercircle.firebasestorage.app',
    iosBundleId: 'com.example.sheHerCircle',
  );
}
